/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gaaapp;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x16354406
 */
public class GaaGUI extends javax.swing.JFrame {

    private Gaa g; //reference variable
    private ArrayList<Gaa> ga; //creating the arraylist
    

    /**
     * Creates new form GaaGUI
     */
    public GaaGUI() {
        initComponents();
        ga = new ArrayList<>(); //instance of the arraylist
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namelbl = new javax.swing.JLabel();
        agelbl = new javax.swing.JLabel();
        teamlbl = new javax.swing.JLabel();
        positionlbl = new javax.swing.JLabel();
        gamesplayedlbl = new javax.swing.JLabel();
        wideslbl = new javax.swing.JLabel();
        goalslbl = new javax.swing.JLabel();
        pointslbl = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        displaybtn = new javax.swing.JButton();
        nametf = new javax.swing.JTextField();
        agetf = new javax.swing.JTextField();
        teamtf = new javax.swing.JTextField();
        positiontf = new javax.swing.JTextField();
        gamesplayedtf = new javax.swing.JTextField();
        widestf = new javax.swing.JTextField();
        goalstf = new javax.swing.JTextField();
        pointstf = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        namelbl.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        namelbl.setText("Name");

        agelbl.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        agelbl.setText("Age");

        teamlbl.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        teamlbl.setText("Team");

        positionlbl.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        positionlbl.setText("Position");

        gamesplayedlbl.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        gamesplayedlbl.setText("Games Played");

        wideslbl.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        wideslbl.setText("Wides");

        goalslbl.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        goalslbl.setText("Goals");

        pointslbl.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        pointslbl.setText("Points");

        addbtn.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        displaybtn.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        displaybtn.setText("Display");
        displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybtnActionPerformed(evt);
            }
        });

        nametf.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        agetf.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        teamtf.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        positiontf.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        gamesplayedtf.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        widestf.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        goalstf.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        pointstf.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GaelicFootball", "Hurling" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gaaapp/gaalogo1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(displaybtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agelbl)
                                    .addComponent(teamlbl)
                                    .addComponent(positionlbl)
                                    .addComponent(gamesplayedlbl)
                                    .addComponent(wideslbl)
                                    .addComponent(goalslbl)
                                    .addComponent(pointslbl)
                                    .addComponent(namelbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pointstf, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(goalstf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(widestf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gamesplayedtf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(positiontf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teamtf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nametf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agetf, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelbl)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agelbl)
                    .addComponent(agetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamlbl)
                    .addComponent(teamtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(positionlbl)
                    .addComponent(positiontf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gamesplayedlbl)
                    .addComponent(gamesplayedtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wideslbl)
                    .addComponent(widestf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goalslbl)
                    .addComponent(goalstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pointslbl)
                    .addComponent(pointstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(displaybtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        //this is for the add button
        //it gets everything that was typed into each textfield
        if (jComboBox1.getSelectedItem().equals("GaelicFootball")) { //this is for the dropbox when gaelic football is selected
            g = new GaelicFootball(); //instance of gaelic foortball
            g.setName(nametf.getText());
            int age = Integer.parseInt(agetf.getText());
            g.setAge(age);
            g.setTeam(teamtf.getText());
            g.setPosition(positiontf.getText());
            ((GaelicFootball) (g)).setGamesPlayed(Integer.parseInt(gamesplayedtf.getText()));
            ((GaelicFootball) (g)).setWides(Integer.parseInt(widestf.getText()));
            ((GaelicFootball) (g)).setGoals(Integer.parseInt(goalstf.getText()));
            ((GaelicFootball) (g)).setPoints(Integer.parseInt(pointstf.getText()));

        } else {
            //adds it as hurling
            g = new Hurling(); //instance of hurling
            g.setName(nametf.getText());
            int age = Integer.parseInt(agetf.getText());
            g.setAge(age);
            g.setTeam(teamtf.getText());
            g.setPosition(positiontf.getText());
            ((Hurling) (g)).setGamesPlayed(Integer.parseInt(gamesplayedtf.getText()));
            ((Hurling) (g)).setWides(Integer.parseInt(widestf.getText()));
            ((Hurling) (g)).setGoals(Integer.parseInt(goalstf.getText()));
            ((Hurling) (g)).setPoints(Integer.parseInt(pointstf.getText()));

        }
        ga.add(g); //adding the info typed in to the array list ga
        writeToFile(ga); //saving everything to the file
    }//GEN-LAST:event_addbtnActionPerformed

    private void displaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybtnActionPerformed
        // TODO add your handling code here:
        //this is for the display button
        //displays all the info that was added to the array list
        for (Gaa g : ga) {
            if (g instanceof GaelicFootball) {
                JOptionPane.showMessageDialog(null, "Gaelic Football, " + g.getName() + ", " + g.getAge() + ", " + g.getTeam() + "," + g.getPosition() + ", " + ((GaelicFootball) g).getGamesPlayed() + ", " + ((GaelicFootball) g).getGoals() + "," + ((GaelicFootball) g).getPoints() + ", " + ((GaelicFootball) g).getWides());

            } else {
                JOptionPane.showMessageDialog(null, "Hurling, " + g.getName() + ", " + g.getAge() + ", " + g.getTeam() + "," + g.getPosition() + ", " + ((Hurling) g).getGamesPlayed() + ", " + ((Hurling) g).getGoals() + "," + ((Hurling) g).getPoints() + ", " + ((Hurling) g).getWides());
            }
        }

    }//GEN-LAST:event_displaybtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:



    }//GEN-LAST:event_jComboBox1ActionPerformed
    //this write all the info that was added to the array list to a file.
    public void writeToFile(ArrayList list) {
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try {
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(ga);

            JOptionPane.showMessageDialog(null, "file written successfully");

            oStream.close();

        } catch (IOException e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GaaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GaaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GaaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GaaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GaaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel agelbl;
    private javax.swing.JTextField agetf;
    private javax.swing.JButton displaybtn;
    private javax.swing.JLabel gamesplayedlbl;
    private javax.swing.JTextField gamesplayedtf;
    private javax.swing.JLabel goalslbl;
    private javax.swing.JTextField goalstf;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametf;
    private javax.swing.JLabel pointslbl;
    private javax.swing.JTextField pointstf;
    private javax.swing.JLabel positionlbl;
    private javax.swing.JTextField positiontf;
    private javax.swing.JLabel teamlbl;
    private javax.swing.JTextField teamtf;
    private javax.swing.JLabel wideslbl;
    private javax.swing.JTextField widestf;
    // End of variables declaration//GEN-END:variables
}
